name: API Tests with Newman


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  vpn_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Newman (Postman CLI) & HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra
                
      - name: Install Chromedriver
        run: npm install -g chromedriver --detect_chromedriver_version
        
      - name: Run Chromedriver on Port 52450 background
        run: chromedriver --port=52450 --url-base=/wd/hub &
        
      - name: Install OpenConnect
        run: sudo apt-get update && sudo apt-get install -y openconnect

      - name: Connect to GlobalProtect VPN
        run: |
          echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect --protocol=gp ${{ secrets.VPN_SERVER }} \
            --user=${{ secrets.VPN_USERNAME }} --passwd-on-stdin --background

      - name: Wait for VPN Connection
        run: sleep 10

      - name: Verify VPN Connection
        run: curl -s ifconfig.me

      - name: Access Target Host
        run: curl -k https://mobileap-uat.aboitizpower.com
        
      - name: Run API Tests
        run: newman run "QA TESTING Payment Channel Routes(Complete flow).postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "ChannelRouteSampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/merged-report.xml --reporter-htmlextra-export docs/merged-report.html &&
             newman run "QA TESTING Payment Complete Flow.postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "sampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/merged-report.xml --reporter-htmlextra-export docs/merged-report.html || echo "Ignoring Newman errors"
      
      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: docs/report_PChannelRoute.xml

      - name: Upload API Test HMTL Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report-html
          path: docs/merged-report.html

      - name: Rename HTML Report File
        run: mv docs/merged-report.html docs/index.html
        
      - name: Commit & Push Report to Main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update API Test Report" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/QiuRRQ/MobileAp-API-Testing.git main
